// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Homework.Domain.Models;

public partial class Function_Page_Mapping
{
    public string FunctionCode { get; set; }

    public string PageCode { get; set; }

    public string PermissionCode { get; set; }

    public virtual RefPermissions FunctionCodeNavigation { get; set; }

    public virtual RefPages PageCodeNavigation { get; set; }

    public virtual RefPermissions PermissionCodeNavigation { get; set; }
}