// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Homework.Domain.Models;

public partial class LogProducts
{
    public long LogProductId { get; set; }

    public long ProductId { get; set; }

    public string ProductCode { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public int StockQty { get; set; }

    public long? CategoryId { get; set; }

    public bool IsActive { get; set; }

    public long? CreatedByUserId { get; set; }

    public string Action { get; set; }

    public DateTime LogTime { get; set; }
}