// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Homework.Domain.Models;

public partial class Orders
{
    public long OrderId { get; set; }

    public string OrderNo { get; set; }

    public DateTime OrderDate { get; set; }

    public decimal TotalAmount { get; set; }

    public string Status { get; set; }

    public long? CreatedByUserId { get; set; }

    public DateTime CreatedTime { get; set; }

    public long? ModifiedByUserId { get; set; }

    public DateTime ModifiedTime { get; set; }

    public long? ApprovedByUserId { get; set; }

    public DateTime? ApprovedTime { get; set; }

    public long? RejectedByUserId { get; set; }

    public DateTime? RejectedTime { get; set; }

    public long? ConfirmedByUserId { get; set; }

    public DateTime? ConfirmedTime { get; set; }

    public virtual Users CreatedByUser { get; set; }

    public virtual Users ModifiedByUser { get; set; }

    public virtual ICollection<OrderItems> OrderItems { get; set; } = new List<OrderItems>();
}