// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Homework.Domain.Models;

public partial class OrderItems
{
    public long OrderItemId { get; set; }

    public long OrderId { get; set; }

    public int Qty { get; set; }

    public decimal Price { get; set; }

    public string OrderItemStatus { get; set; }

    public long? ApprovedByUserId { get; set; }

    public DateTime? ApprovedTime { get; set; }

    public string OrderItemStatusCode { get; set; }

    public long? RejectedByUserId { get; set; }

    public DateTime? RejectedTime { get; set; }

    public string RejectedReason { get; set; }

    public long? ProductId { get; set; }

    public virtual Orders Order { get; set; }

    public virtual Products Product { get; set; }

    public virtual ICollection<ProductStockTransactions> ProductStockTransactions { get; set; } = new List<ProductStockTransactions>();
}