// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Homework.Domain.Models;

public partial class postgresContext : DbContext
{
    public postgresContext(DbContextOptions<postgresContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Function_Page_Mapping> Function_Page_Mapping { get; set; }

    public virtual DbSet<LogOrders> LogOrders { get; set; }

    public virtual DbSet<LogProducts> LogProducts { get; set; }

    public virtual DbSet<LogSystemErrors> LogSystemErrors { get; set; }

    public virtual DbSet<LogUserRoles> LogUserRoles { get; set; }

    public virtual DbSet<OrderItems> OrderItems { get; set; }

    public virtual DbSet<Orders> Orders { get; set; }

    public virtual DbSet<ProductCategoryMapping> ProductCategoryMapping { get; set; }

    public virtual DbSet<Products> Products { get; set; }

    public virtual DbSet<RefCategories> RefCategories { get; set; }

    public virtual DbSet<RefNavbar> RefNavbar { get; set; }

    public virtual DbSet<RefPages> RefPages { get; set; }

    public virtual DbSet<RefPermissions> RefPermissions { get; set; }

    public virtual DbSet<RefRoles> RefRoles { get; set; }

    public virtual DbSet<UserRefreshTokens> UserRefreshTokens { get; set; }

    public virtual DbSet<UserRoleLogs> UserRoleLogs { get; set; }

    public virtual DbSet<UserRoles> UserRoles { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Function_Page_Mapping>(entity =>
        {
            entity.HasKey(e => new { e.FunctionCode, e.PageCode });

            entity.HasIndex(e => e.FunctionCode, "IX_FunctionPage_FunctionCode");

            entity.HasIndex(e => e.PageCode, "IX_FunctionPage_PageCode");

            entity.Property(e => e.FunctionCode).HasMaxLength(100);
            entity.Property(e => e.PageCode).HasMaxLength(50);
            entity.Property(e => e.PermissionCode).HasMaxLength(100);

            entity.HasOne(d => d.FunctionCodeNavigation).WithMany(p => p.Function_Page_MappingFunctionCodeNavigation)
                .HasPrincipalKey(p => p.PermissionCode)
                .HasForeignKey(d => d.FunctionCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FunctionPage_Function");

            entity.HasOne(d => d.PageCodeNavigation).WithMany(p => p.Function_Page_Mapping)
                .HasForeignKey(d => d.PageCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FunctionPage_Page");

            entity.HasOne(d => d.PermissionCodeNavigation).WithMany(p => p.Function_Page_MappingPermissionCodeNavigation)
                .HasPrincipalKey(p => p.PermissionCode)
                .HasForeignKey(d => d.PermissionCode)
                .HasConstraintName("FK_FunctionPage_Permission");
        });

        modelBuilder.Entity<LogOrders>(entity =>
        {
            entity.HasKey(e => e.LogOrderId).HasName("LogOrders_pkey");

            entity.HasIndex(e => e.OrderNo, "LogOrders_OrderNo_key").IsUnique();

            entity.Property(e => e.LogOrderId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.LogTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.OrderDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.OrderNo)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValueSql("'PENDING'::character varying");
            entity.Property(e => e.TotalAmount).HasPrecision(18, 2);
            entity.Property(e => e.VatAmount).HasPrecision(18, 2);
        });

        modelBuilder.Entity<LogProducts>(entity =>
        {
            entity.HasKey(e => e.LogProductId).HasName("LogProducts_pkey");

            entity.HasIndex(e => e.SKU, "LogProducts_SKU_key").IsUnique();

            entity.Property(e => e.LogProductId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Cost).HasPrecision(18, 2);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LogTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Price).HasPrecision(18, 2);
            entity.Property(e => e.SKU)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.StockQty).HasDefaultValue(0);
        });

        modelBuilder.Entity<LogSystemErrors>(entity =>
        {
            entity.HasKey(e => e.LogSystemErrorId).HasName("LogSystemErrors_pkey");

            entity.Property(e => e.LogSystemErrorId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.ErrorCode).HasMaxLength(100);
            entity.Property(e => e.HttpMethod).HasMaxLength(20);
            entity.Property(e => e.Message).IsRequired();
            entity.Property(e => e.Path).HasMaxLength(255);
            entity.Property(e => e.Source).HasMaxLength(255);
        });

        modelBuilder.Entity<LogUserRoles>(entity =>
        {
            entity.HasKey(e => e.LogUserRoleId).HasName("LogUserRoles_pkey");

            entity.Property(e => e.LogUserRoleId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.LogTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.RoleCode).HasMaxLength(50);
            entity.Property(e => e.Username).HasMaxLength(100);
        });

        modelBuilder.Entity<OrderItems>(entity =>
        {
            entity.HasKey(e => e.OrderItemId).HasName("OrderItems_pkey");

            entity.Property(e => e.OrderItemId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Discount).HasPrecision(18, 2);
            entity.Property(e => e.NetAmount).HasPrecision(18, 2);
            entity.Property(e => e.OrderItemStatus)
                .IsRequired()
                .HasMaxLength(30)
                .HasDefaultValueSql("'PENDING'::character varying");
            entity.Property(e => e.OrderItemStatusCode)
                .IsRequired()
                .HasMaxLength(30)
                .HasDefaultValueSql("'PENDING'::character varying");
            entity.Property(e => e.Qty).HasDefaultValue(1);
            entity.Property(e => e.RejectedReason).HasMaxLength(500);
            entity.Property(e => e.UnitPrice).HasPrecision(18, 2);

            entity.HasOne(d => d.Order).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItems_Orders");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItems_Products");
        });

        modelBuilder.Entity<Orders>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("Orders_pkey");

            entity.HasIndex(e => e.OrderNo, "Orders_OrderNo_key").IsUnique();

            entity.Property(e => e.OrderId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.ModifiedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.OrderDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.OrderNo)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValueSql("'PENDING'::character varying");
            entity.Property(e => e.TotalAmount).HasPrecision(18, 2);
            entity.Property(e => e.VatAmount).HasPrecision(18, 2);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.OrdersCreatedByUser)
                .HasForeignKey(d => d.CreatedByUserId)
                .HasConstraintName("FK_Orders_CreatedBy");

            entity.HasOne(d => d.ModifiedByUser).WithMany(p => p.OrdersModifiedByUser)
                .HasForeignKey(d => d.ModifiedByUserId)
                .HasConstraintName("FK_Orders_ModifiedBy");
        });

        modelBuilder.Entity<ProductCategoryMapping>(entity =>
        {
            entity.HasKey(e => e.MappingId).HasName("ProductCategoryMapping_pkey");

            entity.HasIndex(e => e.CategoryId, "IX_ProductCategoryMapping_CategoryId");

            entity.HasIndex(e => e.ProductId, "IX_ProductCategoryMapping_ProductId");

            entity.HasIndex(e => new { e.ProductId, e.CategoryId }, "UQ_ProductCategory").IsUnique();

            entity.HasOne(d => d.Category).WithMany(p => p.ProductCategoryMapping)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_ProductCategory_Category");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductCategoryMapping)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_ProductCategory_Product");
        });

        modelBuilder.Entity<Products>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("Products_pkey");

            entity.HasIndex(e => e.SKU, "Products_SKU_key").IsUnique();

            entity.Property(e => e.ProductId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Cost).HasPrecision(18, 2);
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ModifiedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Price).HasPrecision(18, 2);
            entity.Property(e => e.SKU)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.StockQty).HasDefaultValue(0);

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_Products_RefCategories");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.ProductsCreatedByUser)
                .HasForeignKey(d => d.CreatedByUserId)
                .HasConstraintName("FK_Products_CreatedBy");

            entity.HasOne(d => d.ModifiedByUser).WithMany(p => p.ProductsModifiedByUser)
                .HasForeignKey(d => d.ModifiedByUserId)
                .HasConstraintName("FK_Products_ModifiedBy");
        });

        modelBuilder.Entity<RefCategories>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("Categories_pkey");

            entity.HasIndex(e => e.Name, "Categories_Name_key").IsUnique();

            entity.Property(e => e.CategoryId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.ModifiedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.RefCategoriesCreatedByUser)
                .HasForeignKey(d => d.CreatedByUserId)
                .HasConstraintName("FK_Categories_CreatedBy");

            entity.HasOne(d => d.ModifiedByUser).WithMany(p => p.RefCategoriesModifiedByUser)
                .HasForeignKey(d => d.ModifiedByUserId)
                .HasConstraintName("FK_Categories_ModifiedBy");
        });

        modelBuilder.Entity<RefNavbar>(entity =>
        {
            entity.HasKey(e => e.NavbarCode);

            entity.HasIndex(e => e.PageCode, "IX_RefNavbar_PageCode");

            entity.Property(e => e.NavbarCode).HasMaxLength(50);
            entity.Property(e => e.NavbarIcon).HasMaxLength(100);
            entity.Property(e => e.NavbarName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PageCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Seq).HasDefaultValue(0);

            entity.HasOne(d => d.PageCodeNavigation).WithMany(p => p.RefNavbar)
                .HasForeignKey(d => d.PageCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RefNavbar_RefPages");
        });

        modelBuilder.Entity<RefPages>(entity =>
        {
            entity.HasKey(e => e.PageCode).HasName("RefPages_pkey");

            entity.HasIndex(e => e.PageUrl, "RefPages_PageUrl_key").IsUnique();

            entity.Property(e => e.PageCode).HasMaxLength(50);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PageDesc)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PageUrl)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<RefPermissions>(entity =>
        {
            entity.HasKey(e => e.PermissionId).HasName("Permissions_pkey");

            entity.HasIndex(e => e.PermissionCode, "Permissions_PermissionCode_key").IsUnique();

            entity.Property(e => e.PermissionId).UseIdentityAlwaysColumn();
            entity.Property(e => e.PermissionCode)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PermissionName)
                .IsRequired()
                .HasMaxLength(150);

            entity.HasMany(d => d.PageCode).WithMany(p => p.PermissionCode)
                .UsingEntity<Dictionary<string, object>>(
                    "PermissionPages",
                    r => r.HasOne<RefPages>().WithMany()
                        .HasForeignKey("PageCode")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_PermissionPages_RefPages"),
                    l => l.HasOne<RefPermissions>().WithMany()
                        .HasPrincipalKey("PermissionCode")
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_PermissionPages_RefPermissions"),
                    j =>
                    {
                        j.HasKey("PermissionCode", "PageCode").HasName("PermissionPages_pkey");
                        j.IndexerProperty<string>("PermissionCode").HasMaxLength(100);
                        j.IndexerProperty<string>("PageCode").HasMaxLength(50);
                    });
        });

        modelBuilder.Entity<RefRoles>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("Roles_pkey");

            entity.HasIndex(e => e.RoleCode, "Roles_RoleCode_key").IsUnique();

            entity.Property(e => e.RoleId).UseIdentityAlwaysColumn();
            entity.Property(e => e.RoleCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasMany(d => d.PermissionCode).WithMany(p => p.RoleCode)
                .UsingEntity<Dictionary<string, object>>(
                    "RolePermissions",
                    r => r.HasOne<RefPermissions>().WithMany()
                        .HasPrincipalKey("PermissionCode")
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_RolePermissions_RefPermissions"),
                    l => l.HasOne<RefRoles>().WithMany()
                        .HasPrincipalKey("RoleCode")
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_RolePermissions_RefRoles"),
                    j =>
                    {
                        j.HasKey("RoleCode", "PermissionCode");
                        j.IndexerProperty<string>("RoleCode").HasMaxLength(50);
                        j.IndexerProperty<string>("PermissionCode").HasMaxLength(100);
                    });
        });

        modelBuilder.Entity<UserRefreshTokens>(entity =>
        {
            entity.HasKey(e => e.UserRefreshTokenId).HasName("UserRefreshTokens_pkey");

            entity.HasIndex(e => e.RefreshToken, "UserRefreshTokens_RefreshToken_key").IsUnique();

            entity.Property(e => e.UserRefreshTokenId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.ExpiredTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.RefreshToken).IsRequired();
            entity.Property(e => e.RevokedReason).HasMaxLength(200);

            entity.HasOne(d => d.RevokedByUser).WithMany(p => p.UserRefreshTokensRevokedByUser)
                .HasForeignKey(d => d.RevokedByUserId)
                .HasConstraintName("FK_UserRefreshTokens_RevokedBy");

            entity.HasOne(d => d.User).WithMany(p => p.UserRefreshTokensUser)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRefreshTokens_Users");
        });

        modelBuilder.Entity<UserRoleLogs>(entity =>
        {
            entity.HasKey(e => e.UserRoleLogId).HasName("UserRoleLogs_pkey");

            entity.Property(e => e.UserRoleLogId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.RoleCode)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.RoleCodeNavigation).WithMany(p => p.UserRoleLogs)
                .HasPrincipalKey(p => p.RoleCode)
                .HasForeignKey(d => d.RoleCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoleLogs_RefRoles");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoleLogs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoleLogs_Users");

            entity.HasOne(d => d.UserRole).WithMany(p => p.UserRoleLogs)
                .HasForeignKey(d => d.UserRoleId)
                .HasConstraintName("FK_UserRoleLogs_UserRoles");
        });

        modelBuilder.Entity<UserRoles>(entity =>
        {
            entity.HasKey(e => e.UserRoleId).HasName("UserRoles_pkey");

            entity.HasIndex(e => new { e.UserId, e.RoleCode }, "UQ_UserRoles_User_RoleCode").IsUnique();

            entity.Property(e => e.UserRoleId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.RoleCode)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.ApprovedByUser).WithMany(p => p.UserRolesApprovedByUser)
                .HasForeignKey(d => d.ApprovedByUserId)
                .HasConstraintName("FK_UserRoles_ApprovedBy");

            entity.HasOne(d => d.RoleCodeNavigation).WithMany(p => p.UserRoles)
                .HasPrincipalKey(p => p.RoleCode)
                .HasForeignKey(d => d.RoleCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoles_RefRoles");

            entity.HasOne(d => d.User).WithMany(p => p.UserRolesUser)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoles_Users");
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("Users_pkey");

            entity.HasIndex(e => e.Username, "Users_Username_key").IsUnique();

            entity.Property(e => e.UserId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.LastChecking).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ModifiedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Phone).HasMaxLength(20);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}