// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Homework.Domain.Models;

public partial class ProductVariants
{
    public long ProductVariantId { get; set; }

    public long ProductId { get; set; }

    public string VariantCode { get; set; }

    public string Color { get; set; }

    public string VariantName { get; set; }

    public decimal Price { get; set; }

    public int StockQty { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedTime { get; set; }

    public virtual ICollection<OrderItems> OrderItems { get; set; } = new List<OrderItems>();

    public virtual Products Product { get; set; }
}