// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Homework.Domain.Models;

public partial class ProductCategoryMapping
{
    public long MappingId { get; set; }

    public long ProductId { get; set; }

    public long CategoryId { get; set; }

    public virtual RefCategories Category { get; set; }

    public virtual Products Product { get; set; }
}