// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Homework.Domain.Models;

public partial class ProductStockTransactions
{
    public long ProductStockTransactionId { get; set; }

    public long ProductId { get; set; }

    public long? OrderId { get; set; }

    public long? OrderItemId { get; set; }

    public string TransactionType { get; set; }

    public int Qty { get; set; }

    public string Status { get; set; }

    public string Remark { get; set; }

    public long? CreatedByUserId { get; set; }

    public DateTime CreatedTime { get; set; }

    public virtual Orders Order { get; set; }

    public virtual OrderItems OrderItem { get; set; }

    public virtual Products Product { get; set; }
}