// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Homework.Domain.Models;

public partial class RefPages
{
    public string PageCode { get; set; }

    public string PageDesc { get; set; }

    public string PageUrl { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Function_Page_Mapping> Function_Page_Mapping { get; set; } = new List<Function_Page_Mapping>();

    public virtual ICollection<RefNavbar> RefNavbar { get; set; } = new List<RefNavbar>();

    public virtual ICollection<RefPermissions> PermissionCode { get; set; } = new List<RefPermissions>();
}