// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Homework.Domain.Models;

public partial class Users
{
    public long UserId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int? Age { get; set; }

    public string Phone { get; set; }

    public DateOnly? BirthDate { get; set; }

    public DateTime LastChecking { get; set; }

    public long? CreatedByUserId { get; set; }

    public DateTime CreatedTime { get; set; }

    public long? ModifiedByUserId { get; set; }

    public DateTime ModifiedTime { get; set; }

    public virtual ICollection<Orders> OrdersCreatedByUser { get; set; } = new List<Orders>();

    public virtual ICollection<Orders> OrdersModifiedByUser { get; set; } = new List<Orders>();

    public virtual ICollection<RefCategories> RefCategoriesCreatedByUser { get; set; } = new List<RefCategories>();

    public virtual ICollection<RefCategories> RefCategoriesModifiedByUser { get; set; } = new List<RefCategories>();

    public virtual ICollection<UserRefreshTokens> UserRefreshTokensRevokedByUser { get; set; } = new List<UserRefreshTokens>();

    public virtual ICollection<UserRefreshTokens> UserRefreshTokensUser { get; set; } = new List<UserRefreshTokens>();

    public virtual ICollection<UserRoleLogs> UserRoleLogs { get; set; } = new List<UserRoleLogs>();

    public virtual ICollection<UserRoles> UserRolesApprovedByUser { get; set; } = new List<UserRoles>();

    public virtual ICollection<UserRoles> UserRolesUser { get; set; } = new List<UserRoles>();
}