// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Homework.Domain.Models;

public partial class UserRoleLogs
{
    public long UserRoleLogId { get; set; }

    public long? UserRoleId { get; set; }

    public long UserId { get; set; }

    public DateTime CreatedTime { get; set; }

    public string RoleCode { get; set; }

    public virtual RefRoles RoleCodeNavigation { get; set; }

    public virtual Users User { get; set; }

    public virtual UserRoles UserRole { get; set; }
}