// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Homework.Domain.Models;

public partial class UserRefreshTokens
{
    public long UserRefreshTokenId { get; set; }

    public long UserId { get; set; }

    public string RefreshToken { get; set; }

    public string AccessToken { get; set; }

    public DateTime ExpiredTime { get; set; }

    public DateTime CreatedTime { get; set; }

    public DateTime? RevokedTime { get; set; }

    public long? RevokedByUserId { get; set; }

    public string RevokedReason { get; set; }

    public virtual Users RevokedByUser { get; set; }

    public virtual Users User { get; set; }
}