// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Homework.Domain.Models;

public partial class Category
{
    public long CategoryId { get; set; }

    public string Name { get; set; }

    public long? CreatedByUserId { get; set; }

    public DateTime CreatedTime { get; set; }

    public long? ModifiedByUserId { get; set; }

    public DateTime ModifiedTime { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual User ModifiedByUser { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}