// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Homework.Domain.Models;

public partial class LogSystemError
{
    public long LogSystemErrorId { get; set; }

    public string ErrorCode { get; set; }

    public string Message { get; set; }

    public string StackTrace { get; set; }

    public string Source { get; set; }

    public string Path { get; set; }

    public string HttpMethod { get; set; }

    public long? UserId { get; set; }

    public DateTime CreatedTime { get; set; }
}