// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Homework.Domain.Models;

public partial class LogUserRole
{
    public long LogUserRoleId { get; set; }

    public long UserId { get; set; }

    public string Username { get; set; }

    public long RoleId { get; set; }

    public string RoleCode { get; set; }

    public string Action { get; set; }

    public long? CreatedByUserId { get; set; }

    public DateTime LogTime { get; set; }
}