// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Homework.Domain.Models;

public partial class postgresContext : DbContext
{
    public postgresContext(DbContextOptions<postgresContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Categories> Categories { get; set; }

    public virtual DbSet<LogOrders> LogOrders { get; set; }

    public virtual DbSet<LogProducts> LogProducts { get; set; }

    public virtual DbSet<LogSystemErrors> LogSystemErrors { get; set; }

    public virtual DbSet<LogUserRoles> LogUserRoles { get; set; }

    public virtual DbSet<OrderItems> OrderItems { get; set; }

    public virtual DbSet<Orders> Orders { get; set; }

    public virtual DbSet<Products> Products { get; set; }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<UserRefreshTokens> UserRefreshTokens { get; set; }

    public virtual DbSet<UserRoles> UserRoles { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Categories>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("Categories_pkey");

            entity.HasIndex(e => e.Name, "Categories_Name_key").IsUnique();

            entity.Property(e => e.CategoryId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.ModifiedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.CategoriesCreatedByUser)
                .HasForeignKey(d => d.CreatedByUserId)
                .HasConstraintName("FK_Categories_CreatedBy");

            entity.HasOne(d => d.ModifiedByUser).WithMany(p => p.CategoriesModifiedByUser)
                .HasForeignKey(d => d.ModifiedByUserId)
                .HasConstraintName("FK_Categories_ModifiedBy");
        });

        modelBuilder.Entity<LogOrders>(entity =>
        {
            entity.HasKey(e => e.LogOrderId).HasName("LogOrders_pkey");

            entity.HasIndex(e => e.OrderNo, "LogOrders_OrderNo_key").IsUnique();

            entity.Property(e => e.LogOrderId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.LogTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.OrderDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.OrderNo)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValueSql("'PENDING'::character varying");
            entity.Property(e => e.TotalAmount).HasPrecision(18, 2);
            entity.Property(e => e.VatAmount).HasPrecision(18, 2);
        });

        modelBuilder.Entity<LogProducts>(entity =>
        {
            entity.HasKey(e => e.LogProductId).HasName("LogProducts_pkey");

            entity.HasIndex(e => e.SKU, "LogProducts_SKU_key").IsUnique();

            entity.Property(e => e.LogProductId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Cost).HasPrecision(18, 2);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LogTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Price).HasPrecision(18, 2);
            entity.Property(e => e.SKU)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.StockQty).HasDefaultValue(0);
        });

        modelBuilder.Entity<LogSystemErrors>(entity =>
        {
            entity.HasKey(e => e.LogSystemErrorId).HasName("LogSystemErrors_pkey");

            entity.Property(e => e.LogSystemErrorId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.ErrorCode).HasMaxLength(100);
            entity.Property(e => e.HttpMethod).HasMaxLength(20);
            entity.Property(e => e.Message).IsRequired();
            entity.Property(e => e.Path).HasMaxLength(255);
            entity.Property(e => e.Source).HasMaxLength(255);
        });

        modelBuilder.Entity<LogUserRoles>(entity =>
        {
            entity.HasKey(e => e.LogUserRoleId).HasName("LogUserRoles_pkey");

            entity.Property(e => e.LogUserRoleId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.LogTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.RoleCode).HasMaxLength(100);
            entity.Property(e => e.Username).HasMaxLength(100);
        });

        modelBuilder.Entity<OrderItems>(entity =>
        {
            entity.HasKey(e => e.OrderItemId).HasName("OrderItems_pkey");

            entity.Property(e => e.OrderItemId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Discount).HasPrecision(18, 2);
            entity.Property(e => e.NetAmount).HasPrecision(18, 2);
            entity.Property(e => e.Qty).HasDefaultValue(1);
            entity.Property(e => e.UnitPrice).HasPrecision(18, 2);

            entity.HasOne(d => d.Order).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItems_Orders");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItems_Products");
        });

        modelBuilder.Entity<Orders>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("Orders_pkey");

            entity.HasIndex(e => e.OrderNo, "Orders_OrderNo_key").IsUnique();

            entity.Property(e => e.OrderId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.ModifiedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.OrderDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.OrderNo)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValueSql("'PENDING'::character varying");
            entity.Property(e => e.TotalAmount).HasPrecision(18, 2);
            entity.Property(e => e.VatAmount).HasPrecision(18, 2);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.OrdersCreatedByUser)
                .HasForeignKey(d => d.CreatedByUserId)
                .HasConstraintName("FK_Orders_CreatedBy");

            entity.HasOne(d => d.ModifiedByUser).WithMany(p => p.OrdersModifiedByUser)
                .HasForeignKey(d => d.ModifiedByUserId)
                .HasConstraintName("FK_Orders_ModifiedBy");
        });

        modelBuilder.Entity<Products>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("Products_pkey");

            entity.HasIndex(e => e.SKU, "Products_SKU_key").IsUnique();

            entity.Property(e => e.ProductId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Cost).HasPrecision(18, 2);
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ModifiedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Price).HasPrecision(18, 2);
            entity.Property(e => e.SKU)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.StockQty).HasDefaultValue(0);

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_Products_Categories");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.ProductsCreatedByUser)
                .HasForeignKey(d => d.CreatedByUserId)
                .HasConstraintName("FK_Products_CreatedBy");

            entity.HasOne(d => d.ModifiedByUser).WithMany(p => p.ProductsModifiedByUser)
                .HasForeignKey(d => d.ModifiedByUserId)
                .HasConstraintName("FK_Products_ModifiedBy");
        });

        modelBuilder.Entity<Roles>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("Roles_pkey");

            entity.HasIndex(e => e.RoleCode, "Roles_RoleCode_key").IsUnique();

            entity.Property(e => e.RoleId).UseIdentityAlwaysColumn();
            entity.Property(e => e.RoleCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<UserRefreshTokens>(entity =>
        {
            entity.HasKey(e => e.UserRefreshTokenId).HasName("UserRefreshTokens_pkey");

            entity.HasIndex(e => e.RefreshToken, "UserRefreshTokens_RefreshToken_key").IsUnique();

            entity.Property(e => e.UserRefreshTokenId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.ExpiredTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.RefreshToken).IsRequired();
            entity.Property(e => e.RevokedReason).HasMaxLength(200);

            entity.HasOne(d => d.RevokedByUser).WithMany(p => p.UserRefreshTokensRevokedByUser)
                .HasForeignKey(d => d.RevokedByUserId)
                .HasConstraintName("FK_UserRefreshTokens_RevokedBy");

            entity.HasOne(d => d.User).WithMany(p => p.UserRefreshTokensUser)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRefreshTokens_Users");
        });

        modelBuilder.Entity<UserRoles>(entity =>
        {
            entity.HasKey(e => e.UserRoleId).HasName("UserRoles_pkey");

            entity.HasIndex(e => new { e.UserId, e.RoleId }, "UQ_UserRoles_User_Role").IsUnique();

            entity.Property(e => e.UserRoleId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .HasDefaultValueSql("'ACTIVE'::character varying");

            entity.HasOne(d => d.ApprovedByUser).WithMany(p => p.UserRolesApprovedByUser)
                .HasForeignKey(d => d.ApprovedByUserId)
                .HasConstraintName("FK_UserRoles_ApprovedBy");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.UserRolesCreatedByUser)
                .HasForeignKey(d => d.CreatedByUserId)
                .HasConstraintName("FK_UserRoles_CreatedBy");

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoles_Roles");

            entity.HasOne(d => d.User).WithMany(p => p.UserRolesUser)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoles_Users");
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("Users_pkey");

            entity.HasIndex(e => e.Username, "Users_Username_key").IsUnique();

            entity.Property(e => e.UserId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.LastChecking).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ModifiedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Phone).HasMaxLength(20);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}