// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Homework.Domain.Models;

public partial class postgresContext : DbContext
{
    public postgresContext(DbContextOptions<postgresContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<LogOrder> LogOrders { get; set; }

    public virtual DbSet<LogProduct> LogProducts { get; set; }

    public virtual DbSet<LogSystemError> LogSystemErrors { get; set; }

    public virtual DbSet<LogUserRole> LogUserRoles { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserRefreshToken> UserRefreshTokens { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("Categories_pkey");

            entity.HasIndex(e => e.Name, "Categories_Name_key").IsUnique();

            entity.Property(e => e.CategoryId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.ModifiedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.CategoryCreatedByUsers)
                .HasForeignKey(d => d.CreatedByUserId)
                .HasConstraintName("FK_Categories_CreatedBy");

            entity.HasOne(d => d.ModifiedByUser).WithMany(p => p.CategoryModifiedByUsers)
                .HasForeignKey(d => d.ModifiedByUserId)
                .HasConstraintName("FK_Categories_ModifiedBy");
        });

        modelBuilder.Entity<LogOrder>(entity =>
        {
            entity.HasKey(e => e.LogOrderId).HasName("LogOrders_pkey");

            entity.HasIndex(e => e.OrderNo, "LogOrders_OrderNo_key").IsUnique();

            entity.Property(e => e.LogOrderId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.LogTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.OrderDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.OrderNo)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValueSql("'PENDING'::character varying");
            entity.Property(e => e.TotalAmount).HasPrecision(18, 2);
            entity.Property(e => e.VatAmount).HasPrecision(18, 2);
        });

        modelBuilder.Entity<LogProduct>(entity =>
        {
            entity.HasKey(e => e.LogProductId).HasName("LogProducts_pkey");

            entity.HasIndex(e => e.Sku, "LogProducts_SKU_key").IsUnique();

            entity.Property(e => e.LogProductId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Cost).HasPrecision(18, 2);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LogTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Price).HasPrecision(18, 2);
            entity.Property(e => e.Sku)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("SKU");
            entity.Property(e => e.StockQty).HasDefaultValue(0);
        });

        modelBuilder.Entity<LogSystemError>(entity =>
        {
            entity.HasKey(e => e.LogSystemErrorId).HasName("LogSystemErrors_pkey");

            entity.Property(e => e.LogSystemErrorId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.ErrorCode).HasMaxLength(100);
            entity.Property(e => e.HttpMethod).HasMaxLength(20);
            entity.Property(e => e.Message).IsRequired();
            entity.Property(e => e.Path).HasMaxLength(255);
            entity.Property(e => e.Source).HasMaxLength(255);
        });

        modelBuilder.Entity<LogUserRole>(entity =>
        {
            entity.HasKey(e => e.LogUserRoleId).HasName("LogUserRoles_pkey");

            entity.Property(e => e.LogUserRoleId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.LogTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.RoleCode).HasMaxLength(100);
            entity.Property(e => e.Username).HasMaxLength(100);
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("Orders_pkey");

            entity.HasIndex(e => e.OrderNo, "Orders_OrderNo_key").IsUnique();

            entity.Property(e => e.OrderId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.ModifiedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.OrderDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.OrderNo)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValueSql("'PENDING'::character varying");
            entity.Property(e => e.TotalAmount).HasPrecision(18, 2);
            entity.Property(e => e.VatAmount).HasPrecision(18, 2);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.OrderCreatedByUsers)
                .HasForeignKey(d => d.CreatedByUserId)
                .HasConstraintName("FK_Orders_CreatedBy");

            entity.HasOne(d => d.ModifiedByUser).WithMany(p => p.OrderModifiedByUsers)
                .HasForeignKey(d => d.ModifiedByUserId)
                .HasConstraintName("FK_Orders_ModifiedBy");
        });

        modelBuilder.Entity<OrderItem>(entity =>
        {
            entity.HasKey(e => e.OrderItemId).HasName("OrderItems_pkey");

            entity.Property(e => e.OrderItemId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Discount).HasPrecision(18, 2);
            entity.Property(e => e.NetAmount).HasPrecision(18, 2);
            entity.Property(e => e.Qty).HasDefaultValue(1);
            entity.Property(e => e.UnitPrice).HasPrecision(18, 2);

            entity.HasOne(d => d.Order).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItems_Orders");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItems_Products");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("Products_pkey");

            entity.HasIndex(e => e.Sku, "Products_SKU_key").IsUnique();

            entity.Property(e => e.ProductId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Cost).HasPrecision(18, 2);
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ModifiedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Price).HasPrecision(18, 2);
            entity.Property(e => e.Sku)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("SKU");
            entity.Property(e => e.StockQty).HasDefaultValue(0);

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_Products_Categories");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.ProductCreatedByUsers)
                .HasForeignKey(d => d.CreatedByUserId)
                .HasConstraintName("FK_Products_CreatedBy");

            entity.HasOne(d => d.ModifiedByUser).WithMany(p => p.ProductModifiedByUsers)
                .HasForeignKey(d => d.ModifiedByUserId)
                .HasConstraintName("FK_Products_ModifiedBy");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("Roles_pkey");

            entity.HasIndex(e => e.RoleCode, "Roles_RoleCode_key").IsUnique();

            entity.Property(e => e.RoleId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.RoleCode)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("Users_pkey");

            entity.HasIndex(e => e.Username, "Users_Username_key").IsUnique();

            entity.Property(e => e.UserId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.LastChecking).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ModifiedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Phone).HasMaxLength(20);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<UserRefreshToken>(entity =>
        {
            entity.HasKey(e => e.UserRefreshTokenId).HasName("UserRefreshTokens_pkey");

            entity.HasIndex(e => e.RefreshToken, "UserRefreshTokens_RefreshToken_key").IsUnique();

            entity.Property(e => e.UserRefreshTokenId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.ExpiredTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.RefreshToken).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.UserRefreshTokens)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRefreshTokens_Users");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.RoleId }).HasName("UserRoles_pkey");

            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.UserRoleCreatedByUsers)
                .HasForeignKey(d => d.CreatedByUserId)
                .HasConstraintName("FK_UserRoles_CreatedBy");

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoles_Roles");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoleUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoles_Users");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}