// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Homework.Domain.Models;

public partial class RefPermissions
{
    public long PermissionId { get; set; }

    public string PermissionCode { get; set; }

    public string PermissionName { get; set; }

    public virtual ICollection<Function_Page_Mapping> Function_Page_MappingFunctionCodeNavigation { get; set; } = new List<Function_Page_Mapping>();

    public virtual ICollection<Function_Page_Mapping> Function_Page_MappingPermissionCodeNavigation { get; set; } = new List<Function_Page_Mapping>();

    public virtual ICollection<RefPages> PageCode { get; set; } = new List<RefPages>();

    public virtual ICollection<RefRoles> RoleCode { get; set; } = new List<RefRoles>();
}