// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Homework.Domain.Models;

public partial class UserRole
{
    public long UserId { get; set; }

    public long RoleId { get; set; }

    public long? CreatedByUserId { get; set; }

    public DateTime CreatedTime { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual Role Role { get; set; }

    public virtual User User { get; set; }
}