// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Homework.Domain.Models;

public partial class UserRoles
{
    public long UserId { get; set; }

    public long RoleId { get; set; }

    public long? CreatedByUserId { get; set; }

    public DateTime CreatedTime { get; set; }

    public long UserRoleId { get; set; }

    public string Status { get; set; }

    public long? ApprovedByUserId { get; set; }

    public DateTime? ApprovedTime { get; set; }

    public DateTime? ExpiredTime { get; set; }

    public virtual Users ApprovedByUser { get; set; }

    public virtual Users CreatedByUser { get; set; }

    public virtual Roles Role { get; set; }

    public virtual Users User { get; set; }
}