// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web.Homework.Models;

public partial class FunctionPageMapping
{
    public string FunctionCode { get; set; }

    public string PageCode { get; set; }

    public string PermissionCode { get; set; }

    public virtual RefPermission FunctionCodeNavigation { get; set; }

    public virtual RefPage PageCodeNavigation { get; set; }

    public virtual RefPermission PermissionCodeNavigation { get; set; }
}