// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web.Homework.Models;

public partial class LogOrder
{
    public long LogOrderId { get; set; }

    public long OrderId { get; set; }

    public string OrderNo { get; set; }

    public DateTime OrderDate { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal VatAmount { get; set; }

    public string Status { get; set; }

    public long? CreatedByUserId { get; set; }

    public string Action { get; set; }

    public DateTime LogTime { get; set; }
}