// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web.Homework.Models;

public partial class Order
{
    public long OrderId { get; set; }

    public string OrderNo { get; set; }

    public DateTime OrderDate { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal VatAmount { get; set; }

    public string Status { get; set; }

    public long? CreatedByUserId { get; set; }

    public DateTime CreatedTime { get; set; }

    public long? ModifiedByUserId { get; set; }

    public DateTime ModifiedTime { get; set; }

    public long? ApprovedByUserId { get; set; }

    public DateTime? ApprovedTime { get; set; }

    public long? RejectedByUserId { get; set; }

    public DateTime? RejectedTime { get; set; }

    public long? ConfirmedByUserId { get; set; }

    public DateTime? ConfirmedTime { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual User ModifiedByUser { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}