// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Web.Homework.Models;

public partial class postgresContext : DbContext
{
    public postgresContext(DbContextOptions<postgresContext> options)
        : base(options)
    {
    }

    public virtual DbSet<FunctionPageMapping> FunctionPageMappings { get; set; }

    public virtual DbSet<LogOrder> LogOrders { get; set; }

    public virtual DbSet<LogOrderItem> LogOrderItems { get; set; }

    public virtual DbSet<LogProduct> LogProducts { get; set; }

    public virtual DbSet<LogSystemError> LogSystemErrors { get; set; }

    public virtual DbSet<LogUserRole> LogUserRoles { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductCategoryMapping> ProductCategoryMappings { get; set; }

    public virtual DbSet<RefCategory> RefCategories { get; set; }

    public virtual DbSet<RefNavbar> RefNavbars { get; set; }

    public virtual DbSet<RefPage> RefPages { get; set; }

    public virtual DbSet<RefPermission> RefPermissions { get; set; }

    public virtual DbSet<RefRole> RefRoles { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserRefreshToken> UserRefreshTokens { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<UserRoleLog> UserRoleLogs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<FunctionPageMapping>(entity =>
        {
            entity.HasKey(e => new { e.FunctionCode, e.PageCode });

            entity.ToTable("Function_Page_Mapping");

            entity.HasIndex(e => e.FunctionCode, "IX_FunctionPage_FunctionCode");

            entity.HasIndex(e => e.PageCode, "IX_FunctionPage_PageCode");

            entity.Property(e => e.FunctionCode).HasMaxLength(100);
            entity.Property(e => e.PageCode).HasMaxLength(50);
            entity.Property(e => e.PermissionCode).HasMaxLength(100);

            entity.HasOne(d => d.FunctionCodeNavigation).WithMany(p => p.FunctionPageMappingFunctionCodeNavigations)
                .HasPrincipalKey(p => p.PermissionCode)
                .HasForeignKey(d => d.FunctionCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FunctionPage_Function");

            entity.HasOne(d => d.PageCodeNavigation).WithMany(p => p.FunctionPageMappings)
                .HasForeignKey(d => d.PageCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FunctionPage_Page");

            entity.HasOne(d => d.PermissionCodeNavigation).WithMany(p => p.FunctionPageMappingPermissionCodeNavigations)
                .HasPrincipalKey(p => p.PermissionCode)
                .HasForeignKey(d => d.PermissionCode)
                .HasConstraintName("FK_FunctionPage_Permission");
        });

        modelBuilder.Entity<LogOrder>(entity =>
        {
            entity.HasKey(e => e.LogOrderId).HasName("LogOrders_pkey");

            entity.HasIndex(e => e.OrderNo, "LogOrders_OrderNo_key").IsUnique();

            entity.Property(e => e.LogOrderId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.LogTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.OrderDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.OrderNo)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValueSql("'PENDING'::character varying");
            entity.Property(e => e.TotalAmount).HasPrecision(18, 2);
            entity.Property(e => e.VatAmount).HasPrecision(18, 2);
        });

        modelBuilder.Entity<LogOrderItem>(entity =>
        {
            entity.HasKey(e => e.LogOrderItemId).HasName("LogOrderItems_pkey");

            entity.Property(e => e.LogOrderItemId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Discount).HasPrecision(18, 2);
            entity.Property(e => e.LogTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.NetAmount).HasPrecision(18, 2);
            entity.Property(e => e.OrderItemStatus).HasMaxLength(30);
            entity.Property(e => e.OrderItemStatusCode).HasMaxLength(30);
            entity.Property(e => e.Qty).HasDefaultValue(1);
            entity.Property(e => e.RejectedReason).HasMaxLength(500);
            entity.Property(e => e.UnitPrice).HasPrecision(18, 2);
        });

        modelBuilder.Entity<LogProduct>(entity =>
        {
            entity.HasKey(e => e.LogProductId).HasName("LogProducts_pkey");

            entity.HasIndex(e => e.ProductCode, "LogProducts_SKU_key").IsUnique();

            entity.Property(e => e.LogProductId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Cost).HasPrecision(18, 2);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LogTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Price).HasPrecision(18, 2);
            entity.Property(e => e.ProductCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.StockQty).HasDefaultValue(0);
        });

        modelBuilder.Entity<LogSystemError>(entity =>
        {
            entity.HasKey(e => e.LogSystemErrorId).HasName("LogSystemErrors_pkey");

            entity.Property(e => e.LogSystemErrorId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.ErrorCode).HasMaxLength(100);
            entity.Property(e => e.HttpMethod).HasMaxLength(20);
            entity.Property(e => e.Message).IsRequired();
            entity.Property(e => e.Path).HasMaxLength(255);
            entity.Property(e => e.Source).HasMaxLength(255);
        });

        modelBuilder.Entity<LogUserRole>(entity =>
        {
            entity.HasKey(e => e.LogUserRoleId).HasName("LogUserRoles_pkey");

            entity.Property(e => e.LogUserRoleId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.LogTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.RoleCode).HasMaxLength(50);
            entity.Property(e => e.Username).HasMaxLength(100);
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("Orders_pkey");

            entity.HasIndex(e => e.OrderNo, "Orders_OrderNo_key").IsUnique();

            entity.Property(e => e.OrderId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.ModifiedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.OrderDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.OrderNo)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValueSql("'PENDING'::character varying");
            entity.Property(e => e.TotalAmount).HasPrecision(18, 2);
            entity.Property(e => e.VatAmount).HasPrecision(18, 2);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.OrderCreatedByUsers)
                .HasForeignKey(d => d.CreatedByUserId)
                .HasConstraintName("FK_Orders_CreatedBy");

            entity.HasOne(d => d.ModifiedByUser).WithMany(p => p.OrderModifiedByUsers)
                .HasForeignKey(d => d.ModifiedByUserId)
                .HasConstraintName("FK_Orders_ModifiedBy");
        });

        modelBuilder.Entity<OrderItem>(entity =>
        {
            entity.HasKey(e => e.OrderItemId).HasName("OrderItems_pkey");

            entity.HasIndex(e => e.ProductId, "IX_OrderItems_ProductId");

            entity.Property(e => e.OrderItemId).UseIdentityAlwaysColumn();
            entity.Property(e => e.Discount).HasPrecision(18, 2);
            entity.Property(e => e.NetAmount).HasPrecision(18, 2);
            entity.Property(e => e.OrderItemStatus)
                .IsRequired()
                .HasMaxLength(30)
                .HasDefaultValueSql("'PENDING'::character varying");
            entity.Property(e => e.OrderItemStatusCode)
                .IsRequired()
                .HasMaxLength(30)
                .HasDefaultValueSql("'PENDING'::character varying");
            entity.Property(e => e.Qty).HasDefaultValue(1);
            entity.Property(e => e.RejectedReason).HasMaxLength(500);
            entity.Property(e => e.UnitPrice).HasPrecision(18, 2);

            entity.HasOne(d => d.Order).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItems_Orders");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_OrderItems_Products");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("Products_pkey");

            entity.HasIndex(e => e.ProductCode, "Products_ProductCode_key").IsUnique();

            entity.Property(e => e.ProductId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ModifiedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Price).HasPrecision(18, 2);
            entity.Property(e => e.ProductCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.StockQty).HasDefaultValue(0);
        });

        modelBuilder.Entity<ProductCategoryMapping>(entity =>
        {
            entity.HasKey(e => e.MappingId).HasName("ProductCategoryMapping_pkey");

            entity.ToTable("ProductCategoryMapping");

            entity.HasIndex(e => e.CategoryId, "IX_ProductCategoryMapping_CategoryId");

            entity.HasIndex(e => e.ProductId, "IX_ProductCategoryMapping_ProductId");

            entity.HasIndex(e => new { e.ProductId, e.CategoryId }, "UQ_ProductCategory").IsUnique();

            entity.HasOne(d => d.Category).WithMany(p => p.ProductCategoryMappings)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_ProductCategory_Category");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductCategoryMappings)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductCategory_Product");
        });

        modelBuilder.Entity<RefCategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("Categories_pkey");

            entity.HasIndex(e => e.Name, "Categories_Name_key").IsUnique();

            entity.Property(e => e.CategoryId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.ModifiedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.RefCategoryCreatedByUsers)
                .HasForeignKey(d => d.CreatedByUserId)
                .HasConstraintName("FK_Categories_CreatedBy");

            entity.HasOne(d => d.ModifiedByUser).WithMany(p => p.RefCategoryModifiedByUsers)
                .HasForeignKey(d => d.ModifiedByUserId)
                .HasConstraintName("FK_Categories_ModifiedBy");
        });

        modelBuilder.Entity<RefNavbar>(entity =>
        {
            entity.HasKey(e => e.NavbarCode);

            entity.ToTable("RefNavbar");

            entity.HasIndex(e => e.PageCode, "IX_RefNavbar_PageCode");

            entity.Property(e => e.NavbarCode).HasMaxLength(50);
            entity.Property(e => e.NavbarIcon).HasMaxLength(100);
            entity.Property(e => e.NavbarName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PageCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Seq).HasDefaultValue(0);

            entity.HasOne(d => d.PageCodeNavigation).WithMany(p => p.RefNavbars)
                .HasForeignKey(d => d.PageCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RefNavbar_RefPages");
        });

        modelBuilder.Entity<RefPage>(entity =>
        {
            entity.HasKey(e => e.PageCode).HasName("RefPages_pkey");

            entity.HasIndex(e => e.PageUrl, "RefPages_PageUrl_key").IsUnique();

            entity.Property(e => e.PageCode).HasMaxLength(50);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PageDesc)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PageUrl)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<RefPermission>(entity =>
        {
            entity.HasKey(e => e.PermissionId).HasName("Permissions_pkey");

            entity.HasIndex(e => e.PermissionCode, "Permissions_PermissionCode_key").IsUnique();

            entity.Property(e => e.PermissionId).UseIdentityAlwaysColumn();
            entity.Property(e => e.PermissionCode)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PermissionName)
                .IsRequired()
                .HasMaxLength(150);

            entity.HasMany(d => d.PageCodes).WithMany(p => p.PermissionCodes)
                .UsingEntity<Dictionary<string, object>>(
                    "PermissionPage",
                    r => r.HasOne<RefPage>().WithMany()
                        .HasForeignKey("PageCode")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_PermissionPages_RefPages"),
                    l => l.HasOne<RefPermission>().WithMany()
                        .HasPrincipalKey("PermissionCode")
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_PermissionPages_RefPermissions"),
                    j =>
                    {
                        j.HasKey("PermissionCode", "PageCode").HasName("PermissionPages_pkey");
                        j.ToTable("PermissionPages");
                        j.IndexerProperty<string>("PermissionCode").HasMaxLength(100);
                        j.IndexerProperty<string>("PageCode").HasMaxLength(50);
                    });
        });

        modelBuilder.Entity<RefRole>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("Roles_pkey");

            entity.HasIndex(e => e.RoleCode, "Roles_RoleCode_key").IsUnique();

            entity.Property(e => e.RoleId).UseIdentityAlwaysColumn();
            entity.Property(e => e.RoleCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasMany(d => d.PermissionCodes).WithMany(p => p.RoleCodes)
                .UsingEntity<Dictionary<string, object>>(
                    "RolePermission",
                    r => r.HasOne<RefPermission>().WithMany()
                        .HasPrincipalKey("PermissionCode")
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_RolePermissions_RefPermissions"),
                    l => l.HasOne<RefRole>().WithMany()
                        .HasPrincipalKey("RoleCode")
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_RolePermissions_RefRoles"),
                    j =>
                    {
                        j.HasKey("RoleCode", "PermissionCode");
                        j.ToTable("RolePermissions");
                        j.IndexerProperty<string>("RoleCode").HasMaxLength(50);
                        j.IndexerProperty<string>("PermissionCode").HasMaxLength(100);
                    });
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("Users_pkey");

            entity.HasIndex(e => e.Username, "Users_Username_key").IsUnique();

            entity.Property(e => e.UserId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.LastChecking).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ModifiedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Phone).HasMaxLength(20);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<UserRefreshToken>(entity =>
        {
            entity.HasKey(e => e.UserRefreshTokenId).HasName("UserRefreshTokens_pkey");

            entity.HasIndex(e => e.RefreshToken, "UserRefreshTokens_RefreshToken_key").IsUnique();

            entity.Property(e => e.UserRefreshTokenId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.ExpiredTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.RefreshToken).IsRequired();
            entity.Property(e => e.RevokedReason).HasMaxLength(200);

            entity.HasOne(d => d.RevokedByUser).WithMany(p => p.UserRefreshTokenRevokedByUsers)
                .HasForeignKey(d => d.RevokedByUserId)
                .HasConstraintName("FK_UserRefreshTokens_RevokedBy");

            entity.HasOne(d => d.User).WithMany(p => p.UserRefreshTokenUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRefreshTokens_Users");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => e.UserRoleId).HasName("UserRoles_pkey");

            entity.HasIndex(e => new { e.UserId, e.RoleCode }, "UQ_UserRoles_User_RoleCode").IsUnique();

            entity.Property(e => e.UserRoleId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.RoleCode)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.ApprovedByUser).WithMany(p => p.UserRoleApprovedByUsers)
                .HasForeignKey(d => d.ApprovedByUserId)
                .HasConstraintName("FK_UserRoles_ApprovedBy");

            entity.HasOne(d => d.RoleCodeNavigation).WithMany(p => p.UserRoles)
                .HasPrincipalKey(p => p.RoleCode)
                .HasForeignKey(d => d.RoleCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoles_RefRoles");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoleUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoles_Users");
        });

        modelBuilder.Entity<UserRoleLog>(entity =>
        {
            entity.HasKey(e => e.UserRoleLogId).HasName("UserRoleLogs_pkey");

            entity.Property(e => e.UserRoleLogId).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedTime).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.RoleCode)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.RoleCodeNavigation).WithMany(p => p.UserRoleLogs)
                .HasPrincipalKey(p => p.RoleCode)
                .HasForeignKey(d => d.RoleCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoleLogs_RefRoles");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoleLogs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoleLogs_Users");

            entity.HasOne(d => d.UserRole).WithMany(p => p.UserRoleLogs)
                .HasForeignKey(d => d.UserRoleId)
                .HasConstraintName("FK_UserRoleLogs_UserRoles");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}