// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web.Homework.Models;

public partial class RefNavbar
{
    public string NavbarCode { get; set; }

    public string NavbarName { get; set; }

    public string PageCode { get; set; }

    public int Seq { get; set; }

    public string NavbarIcon { get; set; }

    public virtual RefPage PageCodeNavigation { get; set; }
}