// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web.Homework.Models;

public partial class RefPage
{
    public string PageCode { get; set; }

    public string PageDesc { get; set; }

    public string PageUrl { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<FunctionPageMapping> FunctionPageMappings { get; set; } = new List<FunctionPageMapping>();

    public virtual ICollection<RefNavbar> RefNavbars { get; set; } = new List<RefNavbar>();

    public virtual ICollection<RefPermission> PermissionCodes { get; set; } = new List<RefPermission>();
}