// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web.Homework.Models;

public partial class RefPermission
{
    public long PermissionId { get; set; }

    public string PermissionCode { get; set; }

    public string PermissionName { get; set; }

    public virtual ICollection<FunctionPageMapping> FunctionPageMappingFunctionCodeNavigations { get; set; } = new List<FunctionPageMapping>();

    public virtual ICollection<FunctionPageMapping> FunctionPageMappingPermissionCodeNavigations { get; set; } = new List<FunctionPageMapping>();

    public virtual ICollection<RefPage> PageCodes { get; set; } = new List<RefPage>();

    public virtual ICollection<RefRole> RoleCodes { get; set; } = new List<RefRole>();
}