// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web.Homework.Models;

public partial class RefRole
{
    public long RoleId { get; set; }

    public string RoleCode { get; set; }

    public string RoleName { get; set; }

    public virtual ICollection<UserRoleLog> UserRoleLogs { get; set; } = new List<UserRoleLog>();

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();

    public virtual ICollection<RefPermission> PermissionCodes { get; set; } = new List<RefPermission>();
}