// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web.Homework.Models;

public partial class UserRoleLog
{
    public long UserRoleLogId { get; set; }

    public long? UserRoleId { get; set; }

    public long UserId { get; set; }

    public DateTime CreatedTime { get; set; }

    public string RoleCode { get; set; }

    public virtual RefRole RoleCodeNavigation { get; set; }

    public virtual User User { get; set; }

    public virtual UserRole UserRole { get; set; }
}