// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web.Homework.Models;

public partial class UserRole
{
    public long UserId { get; set; }

    public DateTime CreatedTime { get; set; }

    public long UserRoleId { get; set; }

    public long? ApprovedByUserId { get; set; }

    public DateTime? ApprovedTime { get; set; }

    public DateTime? ExpiredTime { get; set; }

    public string RoleCode { get; set; }

    public virtual User ApprovedByUser { get; set; }

    public virtual RefRole RoleCodeNavigation { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<UserRoleLog> UserRoleLogs { get; set; } = new List<UserRoleLog>();
}