// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web.Homework.Models;

public partial class User
{
    public long UserId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int? Age { get; set; }

    public string Phone { get; set; }

    public DateOnly? BirthDate { get; set; }

    public DateTime LastChecking { get; set; }

    public long? CreatedByUserId { get; set; }

    public DateTime CreatedTime { get; set; }

    public long? ModifiedByUserId { get; set; }

    public DateTime ModifiedTime { get; set; }

    public virtual ICollection<Order> OrderCreatedByUsers { get; set; } = new List<Order>();

    public virtual ICollection<Order> OrderModifiedByUsers { get; set; } = new List<Order>();

    public virtual ICollection<RefCategory> RefCategoryCreatedByUsers { get; set; } = new List<RefCategory>();

    public virtual ICollection<RefCategory> RefCategoryModifiedByUsers { get; set; } = new List<RefCategory>();

    public virtual ICollection<UserRefreshToken> UserRefreshTokenRevokedByUsers { get; set; } = new List<UserRefreshToken>();

    public virtual ICollection<UserRefreshToken> UserRefreshTokenUsers { get; set; } = new List<UserRefreshToken>();

    public virtual ICollection<UserRole> UserRoleApprovedByUsers { get; set; } = new List<UserRole>();

    public virtual ICollection<UserRoleLog> UserRoleLogs { get; set; } = new List<UserRoleLog>();

    public virtual ICollection<UserRole> UserRoleUsers { get; set; } = new List<UserRole>();
}